	-- ESTUDO DO SQL INNER JOIN , SENDO QUE INNER JOIN SERIA PARA JUNTAR DUAS TABELAS DIFERENTE 

	SELECT 
	OP.Identificacao AS 'Nome', -- LEMBRANDO QUE A BOA PRATICA DE POR O AS PARA COLOCAR O APELIDO POIS CASO TENHA COLUNAS COM MESMO NOME EM TABELAS DIFERENTE PODE ACONTECER ERRO SE NÃO DEVIDAMENTE NOMENADO 
	OP.Login ,
	OP.Email_senha AS 'E-mail',
	LJ.Nome,
	LJ.Descricao,
	LJ.Numero
FROM Operadors OP 
INNER JOIN Lojas LJ ON OP.Id_empresa = LJ.EmpresaId
WHERE LJ.Nome = 'LOJA04'
AND OP.Email_senha <> 'NULL'
AND LJ.Numero <> 'NULL'
ORDER BY OP.Identificacao

	-- ESTUDO DO SQL OUTER JOIN , SENDO QUE OUTER JOIN SERIA PARA JUNTAR DUAS TABELAS DIFERENTE QUANDO SÃO IGUAIS OU SE NÃO HOUVER VALORES IGUAIS  ELE IRA TRAZER COMO NULL 

	SELECT 
	OP.Identificacao AS 'NOME' ,
	OP.Login ,
	OP.Email_senha AS 'E-MAIL',
	OP.Data_hora_ultimo_acesso      AS 'DATA DO ULTIMO ACESSO'  ,
	LJ.NOME,
	LJ.DESCRICAO,
	LJ.NUMERO 
	FROM Operadors OP
	    LEFT OUTER JOIN LOJAS LJ ON LJ.EMPRESAID = OP.ID_EMPRESA
		WHERE LJ.Nome = 'LOJA01'
		ORDER BY OP.Identificacao
-- ESTUDO DO SQL OUTER JOIN , SENDO QUE lEFT JOIN SERIA PARA JUNTAR TUDO DA TABELA E OS REGISTRO QUANDO FOR IGUAL DA TABELA 2 SE NÃO TIVER ELE RETORNA NULL 


