/*COMANDO BETWEEN SERVE PARA FILTRAR ENTRE UM VALOR E OUTRO 

O COMANDO IN SERVE PARA  VERIFICAR SE UM VALOR CORRESPONDE COM QUALQUER VALOR PASSADO NA LISTA DE INFORMAÇAO 


NOT USADO PARA  INFORMÇÃO QUE NÃO QUER QUE RETORNE O VALOR QUE ESTAJA DENTRO DO BETWEEN */

SELECT * FROM Operadors
WHERE Data_hora_cadastro BETWEEN '2024-01-30' AND '2025-01-15'

SELECT * 
FROM Operadors
WHERE Identificacao IN ('Alef', 'daniele', 'marianna')

-- COMANDO LIKE  SERVE PARA CONSEGUIR ENCONTRAR MAIS RÁPIDO ALGO QUE NÃO LEMBRE ENTÃO ELE FILTRA O DADOS USANDO O LIKE '....%  EXEMPLO 

SELECT * FROM Operadors
WHERE Identificacao LIKE 'NE%'

--SE O SIMBOLO DE % FOR  NO FINAL ELE BUSCA TUDO QUE VEM ANTES DO SIMBOLO SE FOR NO INICIO BUSCA TUDO QUE FOR DEPOIS DO SIMBOLO EXEMPLO 

SELECT * FROM Operadors
WHERE Identificacao LIKE '%RO'

--SE O SIMBOLO DE % FOR NO INICIO E NO FINAL RETORNARA TUDO QUE FOR ENTRE OS DOIS SIMBOLOS ANTES OU DEPOIS EXEMPLO 

SELECT * FROM Operadors
WHERE Identificacao LIKE '%av%'